import sqlite3 as sql
connection = sql.connect("Hospital.db")
getID = input("Enter new Patient id ")
getName = input("Enter new Name ")
getAdd = input("Enter new Address ")
getPhno = input("Enter new Phone Number ")
getEmail = input("Enter new Email ")
getPincode = input("Enter new Pincode")
result = connection.execute("UPDATE PATIENTS SET NAME='"+getName+"',ADDRESS='"+getAdd+"',PHNO='"+getPhno+"',EMAIL_ID='"+getEmail+"',PINCODE='"+getPincode+"' WHERE ID="+getID)
connection.commit()
print("Entry Updated successfully")
result = connection.execute("SELECT * FROM PATIENTS WHERE ID="+getID)
print("UPDATED SUCCESSFULLY")
for i in result:
    print("id", i[0])
    print("Name", i[1])
    print("Address", i[2])
    print("Phone Number", i[3])
    print("Email", i[4])
    print("Pincode", i[5])